# Generated by Django 5.2.5 on 2025-09-15 07:21

import django.core.validators
from django.db import migrations, models

import reviews.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=256, unique=True, verbose_name="имя"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=25,
                        unique=True,
                        verbose_name="идентификатор",
                    ),
                ),
            ],
            options={
                "verbose_name": "категория",
                "verbose_name_plural": "Категории",
                "ordering": ("name",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="Введите текст комментария",
                        verbose_name="Текст комментария",
                    ),
                ),
                (
                    "pub_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата публикации"
                    ),
                ),
            ],
            options={
                "verbose_name": "Комментарий",
                "verbose_name_plural": "Комментарии",
                "ordering": ["pub_date"],
            },
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=256, unique=True, verbose_name="имя"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=25,
                        unique=True,
                        verbose_name="идентификатор",
                    ),
                ),
            ],
            options={
                "verbose_name": "жанр",
                "verbose_name_plural": "Жанры",
                "ordering": ("name",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="Введите текст отзыва",
                        verbose_name="Текст отзыва",
                    ),
                ),
                (
                    "score",
                    models.PositiveSmallIntegerField(
                        help_text="От 1 до 10",
                        validators=[
                            django.core.validators.MinValueValidator(
                                1, message="Оценка не может быть меньше 1"
                            ),
                            django.core.validators.MaxValueValidator(
                                10, message="Оценка не может быть больше 10"
                            ),
                        ],
                        verbose_name="Оценка",
                    ),
                ),
                (
                    "pub_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата публикации"
                    ),
                ),
            ],
            options={
                "verbose_name": "Отзыв",
                "verbose_name_plural": "Отзывы",
                "ordering": ["-pub_date"],
            },
        ),
        migrations.CreateModel(
            name="Title",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=256)),
                (
                    "year",
                    models.SmallIntegerField(
                        db_index=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                -45836,
                                message="Год выпуска не может быть раньше -45836",
                            ),
                            reviews.validators.validate_year,
                        ],
                    ),
                ),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
    ]
