# Generated by Django 5.2.5 on 2025-09-15 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("reviews", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="review",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="reviews.review",
                verbose_name="Отзыв",
            ),
        ),
        migrations.AddField(
            model_name="title",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="titles",
                to="reviews.category",
            ),
        ),
        migrations.AddField(
            model_name="title",
            name="genre",
            field=models.ManyToManyField(db_index=True, to="reviews.genre"),
        ),
        migrations.AddField(
            model_name="review",
            name="title",
            field=models.ForeignKey(
                help_text="Связь с произведением (Title).",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="reviews.title",
                verbose_name="Произведение",
            ),
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.UniqueConstraint(
                fields=("title", "author"), name="unique_review_per_title"
            ),
        ),
    ]
